### ISSUE TITLE
No more cirrus card or usb on picoreplayer 7 (squeezerlite refuse to start)

### ISSUE THREAD

**Issue by tutle** [piCorePlayer/pCP-Kernels#1]
Hello
With a fresh install of pcp 7, squeezerlite don't start and impossible to activate cirrus card output.
If I try usb (got an amplifier with internal dac), I need to uncheck onboard sound then squeezerlite refuse to start.
No problems on 6.0.1 release of pcp
I upgraded to rasp from 6 to 7 and they seems to work fine.
Strange.

**Comment by paul-1** [comment]
Should be fixed in pCP8

**Comment by tutle** [comment]
Hello Just upgrade to picoreplayer 8. still impossible to have squeezerlite running usb audio with disable internal audio... Help...

**Comment by tutle** [comment]
A friend of mine had the same problem with the same amplifier and he solved by installing mood audio witch seems to recognise the USB SA9023 dac of the amplifier.
https://www.audiophonics.fr/fr/amplificateur-full-digital-fda/fx-audio-d502bt-amplificateur-fda-tas5342a-sortie-subwoofer-bluetooth-50-2x60w-4-ohm-noir-p-14523.html
I don't wan't something else than picoreplayer, how can I solve this problem ?
