### ISSUE TITLE
USB SA9023 problem

### ISSUE THREAD

**Issue by tutle** [piCorePlayer/pCP-Kernels#2]
A friend of mine had the same problem with the same amplifier and he solved by installing moodaudio witch seems to recognise the USB SA9023 dac of the amplifier.
https://www.audiophonics.fr/fr/amplificateur-full-digital-fda/fx-audio-d502bt-amplificateur-fda-tas5342a-sortie-subwoofer-bluetooth-50-2x60w-4-ohm-noir-p-14523.html
I don't wan't something else than picoreplayer, how can I solve this problem ?

**Comment by paul-1** [comment]
Please open a discussion here.
https://forums.slimdevices.com/forumdisplay.php?3-Linux-Unix
