### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by freggal** [piCorePlayer/pCP-Kernels#3]
Many thanks for these helpful scripts. 
The only issue I found was that the make process initially crashed: 

```
make KVER=5.10.77-pcpCore-v7 -j failed. 
gcc: fatal error: Killed signal terminated program cc1
```
Reducing the number of concurrent jobs with:

`make KVER=5.10.77-pcpCore-v7 -j 2`

completed successfully. 

Best Regards

**Comment by paul-1** [comment]
Probably ran out of memory.  Which pi/memory configuration was this?

**Comment by freggal** [comment]
Pi 3B, 4GB. Maybe if I had stopped pCp from running while doing this, it would have helped. No biggie, really.
