### ISSUE TITLE
drv_types.h not found

### ISSUE THREAD

**Issue by sakos** [piCorePlayer/pCP-Kernels#5]
Hello,

I was trying to compile a driver for pCP 8.2.0 to support Wifi dongle TP-LINK TL-W725N with RTL8188 chip. I followed the instructions, however got stuck at step 4. Kernel source is prepared, driver source is present at /mnt/mmcblk0p2/tce/realtek-driversrc folder, makefile is modified. The make command complains about missing drv_types.h file despite this file is available in the "include" subfolder of the driversrc folder.

`tc@pCP:/mnt/mmcblk0p2/tce/realtek-driversrc$ make KVER=5.15.35-pcpCore-v7 -j
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.15.35-pcpCore-v7/build M=/mnt/mmcblk0p2/tce/realtek-driversrc  modules
make[1]: Entering directory '/mnt/mmcblk0p2/tce/kernelsrc'
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_cmd.o
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_security.o
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_debug.o
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_io.o
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_query.o
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_cmd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CC [M]  /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_set.o
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_security.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_security.o] Error 1
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_io.c:47:10: fatal error: drv_types.h: No such file or directory
   47 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_io.o] Error 1
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_debug.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_debug.o] Error 1
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_query.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_query.o] Error 1
/mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_set.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /mnt/mmcblk0p2/tce/realtek-driversrc/core/rtw_ioctl_set.o] Error 1
make[1]: *** [Makefile:1868: /mnt/mmcblk0p2/tce/realtek-driversrc] Error 2
make[1]: Leaving directory '/mnt/mmcblk0p2/tce/kernelsrc'
make: *** [Makefile:2062: modules] Error 2

tc@pCP:/mnt/mmcblk0p2/tce/realtek-driversrc$ ls include/drv_types* -l
-rwxr-xr-x    1 tc       staff        44736 Dec 19 05:19 include/drv_types.h
-rwxr-xr-x    1 tc       staff         2489 Dec 19 05:19 include/drv_types_ce.h
-rwxr-xr-x    1 tc       staff         1367 Dec 19 05:19 include/drv_types_gspi.h
-rwxr-xr-x    1 tc       staff          724 Dec 19 05:19 include/drv_types_linux.h
-rwxr-xr-x    1 tc       staff         7537 Dec 19 05:19 include/drv_types_pci.h
-rwxr-xr-x    1 tc       staff         2516 Dec 19 05:19 include/drv_types_sdio.h
-rwxr-xr-x    1 tc       staff         2542 Dec 19 05:19 include/drv_types_xp.h`

**Comment by paul-1** [comment]
and thus the reason maintaining realtek drivers became unmanageable.  First, which 8188 chipset? there are a couple.   And then what repository are you using for source?

#include <drv_types.h> will only search system default directories or additional ones added to the compile command line.  This is normally handled by the makefile.

Since the PCP file system is just a ram disk, you can copy files without too much concern about a long term muck up.   I would copy the files to the system....  of course they will be gone at next reboot, but your driver will hopefully be compiled by then.

```
cd include
sudo cp drv_types* /usr/include
```

**Comment by sakos** [comment]
Thanks for your quick response Paul. The chipset is 8188EU and I used the recommended repository and branch: 8188eu - https://github.com/aircrack-ng/rtl8188eus [branch "v5.3.9"]
I will copy the files according to your hint ... or buy a new dongle.

**Comment by paul-1** [comment]
Recommended was based on limited research on my part.  Those were the branches used by another maintainer.   Now that I know what you are using, I can try to help with build issues, but I don't hat that chipset to test.

I have built 8821au and 8822bu
