### ISSUE TITLE
Configuring rp4 performance from PiCore

### ISSUE THREAD

**Issue by Santai65** [piCorePlayer/pCP-Kernels#8]
Hi,

I am an absolute beginner with pCP.  Have managed to install and run pCP on a rp4 and have successfully linked by SB devices to this - works perfectly well.

My question and I would appreciate any help please:  Can I access the rp4 OS/GUI from the pCP terminal window - I have managed to get to the pCP window using puTTy and have tried the sudo - raspi-config command.  However get "command not found" - see screen shot
 
![Screenshot 2024-03-11 103525](https://github.com/piCorePlayer/pCP-Kernels/assets/158794763/17fafbee-6241-4b69-a8e4-a12fd093025c)

The reason for wanting to access the rp4 config parameters is to control the on/off for the fan which is now on all the time.

Many thanks

**Comment by paul-1** [comment]
raspi-config is a RaspiOS command.  It is not available on pCP.  I would suggest you take your questions to the forums

https://forums.slimdevices.com/forum/user-forums/linux-unix/111580-announce-picoreplayer-8-0-0

**Comment by Santai65** [comment]
Thanks for your response and guidance, I will do that
